FlaskBlog/App/views.py
import re

from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, g
from sqlalchemy import desc

from .models import *
from .exts import cache

blog = Blueprint('blog', __name__)
admin = Blueprint('admin', __name__)


def get_same_info(page=1, articles=""):
    # 文章分类
    article_type = ArticleType.query.filter().all()
    # 站长推荐
    main_articles = Article.query.order_by(desc("click_num")).all()[:6]
    pagination = ""
    try:
        # 分页
        pagination = articles.paginate(page, per_page=5, error_out=False)
    except:
        pass
    data = {
        "article_type": article_type,
        "main_articles": main_articles,
        'pagination': pagination,
    }
    return data


# 博客首页
@blog.route('/index/<int:page>/')
# @cache.cached(timeout=60 * 3)
def index(page=1):
    articles = Article.query.order_by(desc("create_time"))
    data = {
        "title": "首页",
    }

    data.update(get_same_info(page, articles))
    articles = data['pagination'].items
    data['articles'] = articles
    return render_template("blog/index.html", **data)


@blog.route('/')
def home():
    return redirect(url_for("blog.index", page=1))


# 文章详情
@blog.route('/detail/<int:id>/')
def detail(id):
    article = Article.query.get(id)
    tags = article.tag1
    # 评论列表
    comments = Comment.query.filter_by(article_id=id).all()

    # 下一篇文章
    next_article = Article.query.filter(Article.create_time.__lt__(article.create_time)).all()[-1]

    # 上一篇文章
    prev_article = Article.query.filter(Article.create_time.__gt__(article.create_time)).first()

    # 是否点赞
    likes = article.like
    like = None
    for i in likes:
        if request.remote_addr == i.ip:
            like = i
    # 点击量统计(一个ip15分钟内只能算一个点击)
    # ip个文章id都要算进来
    ip = request.remote_addr
    cache_id = cache.get(id)
    cache_ip = cache.get(ip)
    if not cache_ip or not cache_id:
        cache.set(ip, ip, timeout=60 * 15)
        cache.set(id, id, timeout=60 * 15)
        article.click_num += 1
        db.session.commit()
    data = {
        "title": "文章详情",
        "article": article,
        "tags": tags,
        "comments": comments,
        "prev_article": prev_article,
        "next_article": next_article,
        'likes': likes
    }
    if like:
        data["like_ip"] = like.ip

    data.update(get_same_info())
    return render_template("blog/detail.html", **data)


# 分类列表
@blog.route("/typelist/<int:id>/")
# @cache.cached(timeout=60 * 3)
def typelist(id):
    page = request.args.get('page', 1, type=int)
    type = ArticleType.query.get(id)
    articles = Article.query.filter_by(article_type=type.id).order_by(desc("create_time"))
    data = {
        "articles": articles,
        "title": "首页",
        "typeid": id,
    }
    data.update(get_same_info(page, articles))
    articles = data['pagination'].items
    data['articles'] = articles
    return render_template("blog/typelist.html", **data)


# 文章评论
@blog.route('/article/comment/', methods=['POST'])
def article_comment():
    username = request.form.get("username")
    saytext = request.form.get("saytext")
    article_id = request.form.get("article_id")
    if username == "" or saytext == "":
        data = {
            "code": 1001,
            "msg": "用户名和内容不能为空"
        }
        return jsonify(data)
    comment = Comment.query.filter_by(username=username).first()
    if not comment:
        comment = Comment()
        comment.username = username
        comment.content = saytext
        comment.article_id = article_id
        db.session.add(comment)
        db.session.commit()
        data = {
            "code": 1000,
            "msg": "评论成功",
            "data": {
                "username": comment.username,
                "content": comment.content,
                "time": comment.time,
            }
        }
        return jsonify(data)
    data = {
        "code": 1002,
        "msg": "用户名已存在"
    }
    return jsonify(data)


# 后台管理首页
@admin.route("/admin/index/")
def admin_index():
    articles = Article.query.filter().all()
    comments = Comment.query.filter().all()
    types = ArticleType.query.filter().all()
    tags = Tag.query.filter().all()
    data = {
        "active1": "active",
        "request": request,
        "articles": articles,
        "comments": comments,
        "tags": tags,
        "types": types,
        "user": g.user,
    }
    return render_template("admin/index.html", **data)


# 后台文章管理
@admin.route("/admin/article/<int:page>/")
def admin_article(page):
    pagination = Article.query.order_by(desc("create_time")).paginate(page, per_page=10, error_out=False)
    data = {
        "articles": pagination.items,
        "active2": "active",
        "pagination": pagination,
    }
    return render_template("admin/article.html", **data)


# 后台文章修改
@admin.route("/admin/updatearticle/<int:id>/", methods=["GET", "POST"])
def update_article(id):
    if request.method == "GET":
        article = Article.query.get(id)
        tags = Tag.query.all()
        types = ArticleType.query.all()
        data = {
            "article": article,
            'tags': tags,
            "types": types,
            "active2": "active",
        }
        return render_template("admin/update-article.html", **data)
    elif request.method == "POST":
        # 获取表单提交上来的数据
        title = request.form.get("title")
        content = request.form.get("content")
        tags = request.form.getlist("tags")
        type = request.form.get("category")
        description = request.form.get("describe")
        img = request.form.get("titlepic")
        print(img)
        # 查找对应的文章
        article = Article.query.get(id)
        # 修改数据
        article.title = title
        article.content = content
        article.description = description
        article.img = img
        article.articletype = ArticleType.query.get(type)
        tag_list = []
        for i in tags:
            tag = Tag.query.get(i)
            tag_list.append(tag)
        article.tag1 = tag_list
        # 提交
        db.session.commit()
        return redirect(url_for("admin.update_article", id=id))


# 后台文章删除
@admin.route('/admin/delarticle/')
def del_article():
    article_id = request.args.get("article_id")
    article = Article.query.get(article_id)
    data = {
        "code": 1000,
        "msg": ""
    }
    if not article:
        data['code'] = 1002
        data['msg'] = "文章不存在！"
        return jsonify(data)
    try:
        db.session.delete(article)
        db.session.commit()
    except:
        data['code'] = 1001
        data['msg'] = "删除失败请重试！"
        return jsonify(data)
    data['msg'] = "文章删除成功！"
    return jsonify(data)


# 后台文章增加
@admin.route('/admin/addarticle/', methods=["GET", "POST"])
def add_article():
    if request.method == "GET":
        tags = Tag.query.all()
        types = ArticleType.query.all()
        data = {
            'tags': tags,
            "active2": "active",
            "types": types,
        }
        return render_template("admin/add-article.html", **data)
    elif request.method == "POST":
        # 获取表单提交上来的数据
        title = request.form.get("title")
        content = request.form.get("content")
        tags = request.form.getlist("tags")
        type = request.form.get("category")
        description = request.form.get("describe")
        img = request.form.get("titlepic")
        article = Article()
        # 新增数据
        article.title = title
        article.content = content
        article.description = description
        article.img = img
        article.create_time = datetime.datetime.now()
        article.articletype = ArticleType.query.get(type)
        tag_list = []
        for i in tags:
            tag = Tag.query.get(i)
            tag_list.append(tag)
        article.tag1 = tag_list
        # 提交
        db.session.commit()
        return redirect(url_for("admin.admin_article", page=1))


# 后台文章删除全部
@admin.route("/admin/delallarticle/", methods=["POST"])
def del_all_article():
    article_ids = request.form.getlist("checkbox[]")

    for i in article_ids:
        article = Article.query.get(i)
        db.session.delete(article)
        db.session.commit()
    return redirect(url_for("admin.admin_article", page=1))


# 后台分类管理
@admin.route('/admin/type/')
def admin_type():
    types = ArticleType.query.filter().all()
    data = {
        "types": types,
        "active3": "active",
    }
    return render_template("admin/category.html", **data)


# 后台分类增加
@admin.route('/admin/addtype/', methods=['POST'])
def type_add():
    name = request.form.get("name")
    cname = request.form.get("cname")
    data = {
        "code": 1000,
        "msg": "NO",
    }
    type = ArticleType.query.filter_by(name=name).first()
    if not type:
        type = ArticleType()
        type.name = name
        type.cname = cname
        try:
            db.session.add(type)
            db.session.commit()
            data['msg'] = "添加成功！"
            data['id'] = type.id
        except:
            data['code'] = 1001
            data['msg'] = "添加失败请重试！"

            return jsonify(data)
        return jsonify(data)
    data['msg'] = "分类已存在！"
    return jsonify(data)


# 后台分类删除
@admin.route('/admin/deltype/', methods=['POST'])
def dle_type():
    type_id = request.form.get("type_id")
    data = {
        "code": 1000,
        "msg": "nice",
    }
    type = ArticleType.query.filter_by(id=type_id).first()
    if type:
        db.session.delete(type)
        db.session.commit()
        data['msg'] = "删除成功"
        return jsonify(data)
    data['code'] = 1001
    data['msg'] = "此分类不存在"
    return jsonify(data)


# 后台分类修改
@admin.route('/admin/updatetype/<int:id>/', methods=["POST", "GET"])
def update_type(id):
    if request.method == "GET":
        type = ArticleType.query.get(id)
        data = {
            "active3": "active",
            "type": type,
        }
        return render_template("admin/update-category.html", **data)

FlaskBlog/templates/blog/base.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青"/>
    <meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/blog/css/base.css" rel="stylesheet">
    <link href="/static/blog/css/index.css" rel="stylesheet">
    <link href="/static/blog/css/m.css" rel="stylesheet">
    {% block myCss %}

    {% endblock %}
    <script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/blog/js/comm.js"></script>
    <!--[if lt IE 9]>
<script src="/static/blog/js/modernizr.js"></script>
<![endif]-->


</head>
<body>
<header class="header-navigation" id="header">
    <nav>
        <div class="logo"><a href="/">个人博客</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
            <li><a href="/">网站首页</a></li>
{#            <li><a href="share.html">我的相册</a></li>#}
            <li><a href="list.html">我的日记</a></li>
            <li><a href="about.html">关于我</a></li>
            <li><a href="gbook.html">留言</a></li>
{#            <li><a href="info.html">内容页</a></li>#}
{#            <li><a href="infopic.html">内容页</a></li>#}
        </ul>
    </nav>
</header>
<article>
    <aside class="l_box">
        {#        <div class="about_me">#}
        {#            <h2>关于我</h2>#}
        {#            <ul>#}
        {#                <i><img src="/static/blog/images/4.jpg"></i>#}
        {#                <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>#}
        {#            </ul>#}
        {#        </div>#}
        {#        <div class="wdxc">#}
        {#            <h2>我的相册</h2>#}
        {#            <ul>#}
        {#                <li><a href="/"><img src="/static/blog/images/7.jpg"></a></li>#}
        {#                <li><a href="/"><img src="/static/blog/images/8.jpg"></a></li>#}
        {#                <li><a href="/"><img src="/static/blog/images/9.jpg"></a></li>#}
        {#                <li><a href="/"><img src="/static/blog/images/10.jpg"></a></li>#}
        {#                <li><a href="/"><img src="/static/blog/images/11.jpg"></a></li>#}
        {#                <li><a href="/"><img src="/static/blog/images/12.jpg"></a></li>#}
        {#            </ul>#}
        {#        </div>#}
        <div class="search">
            <form action="" method="post" name="searchform" id="searchform">
                <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词"
                       style="color: rgb(153, 153, 153);"
                       onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}"
                       onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                <input name="show" value="title" type="hidden">
                <input name="tempid" value="1" type="hidden">
                <input name="tbname" value="news" type="hidden">
                <input name="Submit" class="input_submit" value="搜索" type="submit">
            </form>
        </div>
        <div class="fenlei">
            <h2>文章分类</h2>
            <ul>
                {% for type in article_type %}
                    <li>
                        <a href="{{ url_for("blog.typelist", id=type.id) }}">{{ type.name }}（{{ type.articles | length }}）</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="tuijian">
            <h2>站长推荐</h2>
            <ul>
                {% for main_article in main_articles %}
                    <li><a href="{{ url_for("blog.detail", id=main_article.id) }}">{{ main_article.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="links">
            <h2>友情链接</h2>
            <ul>
                <a href="http://www.wcyq.xyz/" target="_blank">魏诚的学习笔记</a>
                <a href="https://blog.csdn.net/qq_43475458" target="_blank">进步缓慢的cxy</a>
            </ul>
        </div>
        <div class="guanzhu">
            <h2>关注我 么么哒</h2>
            <ul>
                <img src="/static/blog/images/wx.jpg">
            </ul>
        </div>
    </aside>
    {% block r_box %}

    {% endblock %}

</article>
<footer>
    <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% block myJs %}

{% endblock %}
</body>
</html>

FlaskBlog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block myCss %}
    <link href="/static/blog/css/info.css" rel="stylesheet">
{% endblock %}

{% block r_box %}
    <main>
        <div class="infosbox">
            <div class="newsview">
                <h3 class="news_title">{{ article.title }}</h3>
                <div class="bloginfo">
                    <ul>
                        <li class="author">
                            作者：<a href="/">wc</a>
                        </li>
                        <li class="lmname">
                            <a href="{{ url_for("blog.typelist", id= article.articletype.id) }}" target="_self">
                                {{ article.articletype.name }}
                            </a>
                        </li>
                        <li class="timer">时间：{{ article.create_time }}</li>
                        <li class="view">{{ article.click_num }}人已阅读</li>
                    </ul>
                </div>
                <div class="tags">
                    {% for tag in tags %}
                        <a href="/" target="_blank">{{ tag.name }}</a> &nbsp;
                    {% endfor %}
                </div>
                <div class="news_about"><strong>简介</strong>
                    {{ article.description }}
                </div>
                <div class="news_con">
                    {{ article.content | safe }}
                </div>
            </div>
            <div class="share">
                <p class="diggit" id="like"><a href="">很赞哦！ </a>(<b id="diggnum">{{ likes | length }}</b>)
                </p>
            </div>
            <div class="nextinfo">
                {% if prev_article %}
                    <p>上一篇：<a href="{{ url_for("blog.detail", id=prev_article.id) }}">{{ prev_article.title }}</a></p>
                {% else %}
                    <p><a href="{{ url_for("blog.home") }}">返回列表</a></p>
                {% endif %}

                {% if next_article %}
                    <p>下一篇：<a href="{{ url_for("blog.detail", id=next_article.id) }}">{{ next_article.title }}</a></p>
                {% else %}
                    <p><a href="{{ url_for("blog.home") }}">返回列表</a></p>
                {% endif %}

            </div>
            <div class="news_pl">
                <h2>文章评论</h2>
                <div class="gbko">
                    <script src="/e/pl/more/?classid=77&amp;id=106&amp;num=20"></script>
                    {% for comment in comments %}
                        <div class="fb">
                            <ul>
                                <p class="fbtime"><span>{{ comment.time }}</span>{{ comment.username }}</p>
                                <p class="fbinfo">{{ comment.content }}</p>
                            </ul>
                        </div>
                    {% endfor %}
                    <script>
                        function CheckPl(obj) {
                            if (obj.saytext.value == "") {
                                alert("您没什么话要说吗？");
                                obj.saytext.focus();
                                return false;
                            }
                            return true;
                        }
                    </script>
                    <form action="{{ url_for("blog.article_comment") }}" method="post" name="saypl" id="saypl"
                          onsubmit="return CheckPl(document.saypl)">
                        <div id="plpost">
                            <p class="saying"><span><a href="">共有<script
                                    type="text/javascript"
                                    src="/e/public/ViewClick/?classid=77&amp;id=106&amp;down=2"></script>{{ comments | length }}条评论</a></span>来说两句吧...
                            </p>
                            <p class="yname"><span>用户名:</span>
                                <input name="username" type="text" class="inputText" id="username" value="" size="16">
                            </p>
                            {#                            <p class="yzm"><span>验证码:</span>#}
                            {#                                <input name="key" type="text" class="inputText" size="16">#}
                            {#                            </p>#}
                            {#                            <input name="nomember" type="hidden" id="nomember" value="1" checked="checked">#}
                            <textarea name="saytext" rows="6" id="saytext"></textarea>
                            <input type="hidden" name="article_id" id="article_id" value="{{ article.id }}">
                            <input name="imageField" type="submit" value="提交" id="submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

{% block myJs %}
    <script>

        $(function () {
            // 提交评论
            $('#submit').click(function () {
                username = $("#username").val();
                saytext = $("#saytext").val();
                article_id = $("#article_id").val();
                data = {
                    username: username,
                    saytext: saytext,
                    article_id: article_id,
                };


                $.post("/article/comment/", data = data, function (data) {
                    if (data.code == 1000) {
                        gbko = $(".gbko");
                        gbko.prepend("<div class=\"fb\">\n" +
                            "                            <ul>\n" +
                            "                                <p class=\"fbtime\"><span>" + data.data.time + "</span>" + data.data.username + "</p>\n" +
                            "                                <p class=\"fbinfo\">" + data.data.content + "</p>\n" +
                            "                            </ul>\n" +
                            "                        </div>");
                        alert(data.msg);

                        $(".saying").find("a").html("共有" + $(".fb").length + "条评论");
                    } else if (data.code == 1001) {
                        alert(data.msg);
                    } else {
                        alert(data.msg);
                    }
                });
                $("#username").val("");
                $("#saytext").val("");
                return false;
            })

            // 是否点赞
            var like_ip = `{{ like_ip }}`;
            if (like_ip != `{{ request.remote_addr }}`) {
                $("#like").addClass("not-like");
            }

            $("#like").click(function () {
                var a_id = `{{ article.id }}`;
                data = {
                    a_id: a_id,
                };

                var num = parseInt($("#diggnum").html())
                $.post('/articlelike/', data = data, function (data) {
                    if (data.code == 1) {
                        $("#like").removeClass("not-like");
                        $("#diggnum").html(num + 1);
                    } else {
                        $("#like").addClass("not-like");
                        $("#diggnum").html(num - 1);
                    }
                });
                return false;
            })

        })

    </script>
{% endblock %}

FlaskBlog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block r_box %}
    <main class="r_box">
        {% for article in articles %}
            <li><i><a href="{{ article.img }}" target="_blank"><img src="{{ article.img }}"></a></i>
                <h3><a href="{{ url_for("blog.detail", id=article.id) }}">{{ article.title }}</a></h3>
                <p>{{ article.description }}</p>
            </li>
        {% endfor %}
        <div class="pagelist">
            <a href="{{ url_for("blog.index", page=1) }}">首页</a>
            {% if pagination.has_prev %}
                  <a href="{{ url_for("blog.index", page=pagination.prev_num) }}" onclick="page({{ pagination.prev_num }})">上一页</a>
            {% endif %}

            {% for iter_page in pagination.iter_pages() %}
                {% if iter_page == pagination.page %}
                    <a href="{{ url_for("blog.index", page=iter_page) }}" class="curPage">{{ iter_page }}</a>&nbsp;&nbsp;
                {% else %}
                    <a href="{{ url_for("blog.index", page=iter_page) }}" onclick="page({{ iter_page }})">{{ iter_page }}</a>&nbsp;&nbsp;
                {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
                <a href="{{ url_for("blog.index", page=pagination.next_num) }}" onclick="page({{ pagination.next_num }})">下一页</a>
            {% endif %}

            <a href="{{ url_for("blog.index", page=pagination.pages) }}">尾页</a>
        </div>
    </main>
{% endblock %}

FlaskBlog/templates/blog/typelist.html
{% extends 'blog/base.html' %}
{% block r_box %}
    <main class="r_box">
        {% for article in articles %}

            <li>
                <i><a href="{{ article.img }}" target="_blank"><img src="{{ article.img }}"></a></i>
                <h3><a href="{{ url_for("blog.detail", id=article.id) }}">{{ article.title }}</a></h3>
                <p>{{ article.description }}</p>
            </li>
        {% endfor %}
        <div class="pagelist">
            <a href="{{ url_for("blog.typelist", id=typeid) }}?page={{ 1 }}">首页</a>
            {% if pagination.has_prev %}
                <a href="{{ url_for("blog.typelist", id=typeid) }}?page={{ pagination.prev_num }}"
                   onclick="page({{ pagination.prev_num }})">上一页</a>
            {% endif %}

            {% for iter_page in pagination.iter_pages() %}
                {% if iter_page == pagination.page %}
                    <a href="{{ url_for("blog.typelist", id=typeid) }}?page={{ iter_page }}" class="curPage">{{ iter_page }}</a>
                    &nbsp;&nbsp;
                {% else %}
                    <a href="{{ url_for("blog.typelist", id=typeid) }}?page={{ iter_page }}"
                       onclick="page({{ iter_page }})">{{ iter_page }}</a>&nbsp;&nbsp;
                {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
                <a href="{{ url_for("blog.typelist", id=typeid) }}?page={{ pagination.next_num }}"
                   onclick="page({{ pagination.next_num }})">下一页</a>
            {% endif %}

            <a href="{{ url_for("blog.typelist", id=typeid) }}?page={{ pagination.pages }}">尾页</a>
        </div>
    </main>
{% endblock %}